# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('uwb-module-example', ['uwb-module'])
    obj.source = 'uwb-module-example.cc'

	obj = bld.create_ns3_program('uwb-module-phy-example', ['uwb-module'])
    obj.source = 'uwb-module-phy-example.cc'

	obj = bld.create_ns3_program('uwb-module-ranging-example', ['uwb-module'])
    obj.source = 'uwb-module-ranging-example.cc'

